### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by zero734kr** [choshinyoung/watermelon#2]
Hello,

Is there a page to check leaderboard of [Watermelon Game](https://watermelon.shinyoung.tech)?
Or is this still being implemented?

Thank you for a nice game! 👍

**Comment by choshinyoung** [comment]
리더보드 구현 계획은 없습니다
게임 오버 화면을 잘 캡쳐해서 저장해주세요

제 게임을 재밌게 플레이해주셔서 감사합니다!

**Comment by zero734kr** [comment]
넵
