### ISSUE TITLE
Total play count

### ISSUE THREAD

**Issue by 19thchance** [choshinyoung/watermelon#3]
![image](https://user-images.githubusercontent.com/63943594/110204618-567bc900-7eb7-11eb-8f11-ed8efc9e7eb7.png)
It seems to have a bug in processing the total play count.

**Comment by choshinyoung** [comment]
무슨 버그요

**Comment by 19thchance** [comment]
> 무슨 버그요

전 405번 웹사이트에 들어가본적이 없고
막 가끔씩은 2번씩 늘던데요..?

**Comment by choshinyoung** [comment]
저런

**Comment by ERRrOR404** [comment]
..?
